import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  site: 'https://blog.wuto.site',
  base: '',
  trailingSlash: 'always',
  // Sitemap is generated by src/pages/sitemap.xml.ts (hand-rolled, version-safe).
  // We dropped @astrojs/sitemap because its 3.4+ release relies on the
  // `astro:routes:resolved` hook that only exists in Astro 5.x.

  build: {
    // Output /blog/<slug>/index.html so URL `/blog/<slug>/` matches the old Jekyll permalink exactly
    format: 'directory',
  },

  markdown: {
    shikiConfig: {
      // Dark syntax theme; the site itself can be dark or light via JS toggle
      theme: 'github-dark-dimmed',
      wrap: true,
    },
    // Chinese punctuation usually doesn't benefit from smartypants
    smartypants: false,
  },
});
